### ISSUE TITLE
Not possible to run the kamus-cli when installing from npm

### ISSUE THREAD

**Issue by alibengtsson** [Soluto/kamus#113]
when installing the kamus-cli on local computer i executed the following command

npm install -g @soluto-asurion/kamus-cli

when executing the cli kamus-cli only i get the following error:

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/bin/kamus-cli:3:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

**Comment by shaikatz** [comment]
Thanks @alibengtsson,
I'll take a look into that.

**Comment by shaikatz** [comment]
I did some tests, for me the latest version from npmjs works corretly.
I've read a bit about this issue, it might be related to faulty installation of npm which may lead to issues with global packages, (/usr/bin) is not the default NPM modules folder.

Can you try reinstalling NPM with default values and then reinstall kamus-cli?

**Comment by alibengtsson** [comment]
I have confirmed on my side again, you are correct. please close this ticket.

**Comment by shaikatz** [comment]
Happy to hear that you've solved it.
